version: '3.8'

services:
  mongodb:
    image: mongo:7.0.8
    container_name: gestion_stock_mongodb
    restart: always
    ports:
      - "8096:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: motdepasse
    volumes:
      - mongo_data:/data/db

  web:
    build: .
    container_name: gestion_stock_web
    restart: always
    ports:
      - "8087:80"
    depends_on:
      - mongodb
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_USER: admin
      MONGO_PASSWORD: motdepasse

volumes:
  mongo_data:
